version: '3.7'

services:

  gateway-api:
    container_name: gateway-api
    image: ibm-cloud-academy/gateway-api:v1
    restart: always
    hostname: GatewayApi
    ports:
      - "8080:8080"
    networks:
      - back-tier

  service-registry:
    container_name: service-registry
    image: ibm-cloud-academy/service-registry:v1
    restart: always
    ports:
      - "8761:8761"
    networks:
      - back-tier

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    hostname: Prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - back-tier

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    hostname: Grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/config/provisioning/:/etc/grafana/provisioning/
    networks:
      - back-tier

  serviceA:
    container_name: serviceA
    image: ibm-cloud-academy/service_a:v1
    restart: always
    hostname: ServiceA
    networks:
      - back-tier

  db_service_a:
    container_name: db_service_a
    image: mysql:latest
    environment:
      MYSQL_DATABASE: service_a
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql_db_service_a
    networks:
      - back-tier

  serviceB:
    container_name: serviceB
    image: ibm-cloud-academy/service_b:v1
    restart: always
    hostname: ServiceB
    networks:
      - back-tier

  db_service_b:
    container_name: db_service_b
    image: mysql:latest
    environment:
      MYSQL_DATABASE: service_b
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql_db_service_b
    networks:
      - back-tier

  serviceC:
    container_name: serviceC
    image: ibm-cloud-academy/service_c:v1
    restart: always
    hostname: ServiceC
    networks:
      - back-tier
  
  db_service_c:
    container_name: db_service_c
    image: mysql:latest
    environment:
      MYSQL_DATABASE: service_c
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql_db_service_c
    networks:
      - back-tier

  serviceD:
    container_name: serviceD
    image: ibm-cloud-academy/service_d:v1
    restart: always
    hostname: ServiceD
    networks:
      - back-tier
  
  db_service_d:
    container_name: db_service_d
    image: mysql:latest
    environment:
      MYSQL_DATABASE: service_d
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql_db_service_d
    networks:
      - back-tier

networks:
  back-tier: