{
 "title": "Prima dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  { "title": "Resilience4j", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "buffered_calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calls_second_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "prometheus_http_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "targets": [
      { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "prometheus_http_request_duration_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 6, "y": 18 },
     "targets": [
      {
       "expr": "prometheus_http_request_duration_seconds_bucket",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}