spring:
  application:
    name: serviceC

server:
  port: 0

serviceDUrl: http://serviceD/serviceD

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"