spring:
  application:
    name: gatewayapi
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: serviceA
          uri: lb://serviceA/
          predicates:
            - Path=/serviceA/**
          filters:
            - name: CircuitBreaker
              args:
                name: breakerGatewayToA
                fallbackUri: forward:/fallback/gatewayfallback
                # Configure the WebClient filter to propagate exceptions
                #exceptionHandler: true #Per far passare l'eccezione come parametro del controller forward:/fallback/gatewayfallback
                tags:
                  group: myCircuitBreakerGroup
            
serviceAUrl: http://serviceA
    
gatewayFallback: forward:/fallback/gatewayfallback    
    
server:
  port: 8080

# Utilizzato per fornire la posizione dell' Eureka Discovery Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"