spring:
  application:
    name: serviceB

server:
  port: 0

serviceCUrl: http://serviceC/serviceC

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"